### ISSUE TITLE
No need of catching HTTPError Unauthorized for url .../api/users/me

### ISSUE THREAD

**Issue by CesMak** [miguelgrinberg/microflack_tokens#7]
Hey Miguel,

I just realized that you do not catch the following error:
```
  File "/home/markus/Documents/06_Software_Projects/idm/microflack_tokens/app.py", line 26, in verify_password
    r = requests.get('/api/users/me', auth=(nickname, password))
  File "/home/markus/Documents/06_Software_Projects/idm/microflack_tokens/env/lib/python3.8/site-packages/microflack_common/requests.py", line 57, in get
    return _make_request('get', url, *args, **kwargs)
  File "/home/markus/Documents/06_Software_Projects/idm/microflack_tokens/env/lib/python3.8/site-packages/microflack_common/requests.py", line 40, in _make_request
    response.raise_for_status()
  File "/home/markus/Documents/06_Software_Projects/idm/microflack_tokens/env/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: http://192.168.178.26/api/users/me
```

Does this has any specific reason? 
The error is thrown in line 26 (before evaluation of the status_code is done). 

I changed now the code like this in tokens -> app.py

```
from requests.exceptions import HTTPError
...
    try:
        r = requests.get('/api/users/me', auth=(nickname, password))
    except HTTPError as e:
        print(e)
        return False
```

But I guess it makes more sense to include a try except block in the common requests.py file or?

**Comment by miguelgrinberg** [comment]
The functions in `requests` only raise an error if you pass `raise_for_status=True`. The default for this argument is `False`, thought, so in the default cause there shouldn't be an HTTPError raised. Have you changed anything in the requests.py file?

**Comment by CesMak** [comment]
No I did not change anything in the requests.py file (its still the same as here: https://github.com/miguelgrinberg/microflack_common/blob/master/microflack_common/requests.py). 

But is this error crucial? In case my credentials are wrong what else should be returned by  r = requests.get('/api/users/me', auth=(nickname, password))? 
Do you have any hints for me how to debug or handle this error?

**Comment by miguelgrinberg** [comment]
Here is the place where this error is raised: https://github.com/miguelgrinberg/microflack_common/blob/master/microflack_common/requests.py#L39-L40.

For the error to be raised the `raise_for_status` argument must be `True`. You can see in the function that I linked that the default is `False`. You need to figure out why this variable is True for you. You can add some print/logging statements in this function as a start.

**Comment by CesMak** [comment]
Ok I found the problem. Inside the wheels in requests.py the line was always:
`    raise_for_status = kwargs.pop('raise_for_status', True)`

I think this is due to the fact that you updated requests.py but a new tag v.5 for correct wheels should have been released too or?

![image](https://user-images.githubusercontent.com/20240718/99355440-92f3cc80-28a8-11eb-8f18-34e7fbcd1279.png)


Issue can be closed....

**Comment by miguelgrinberg** [comment]
Great, thanks for providing the results of your research.
